# Generated by Django 3.2.9 on 2021-11-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=100)),
                ('courseimg', models.ImageField(upload_to='corsePics')),
                ('coursedesc', models.TextField()),
            ],
        ),
    ]
