# Generated by Django 3.2.9 on 2021-11-11 11:03

# from django.db import migrations, models


# class Migration(migrations.Migration):

#      dependencies = [
#         ('app', '0001_initial'),
#     ]

#     operations = [
#         migrations.CreateModel(
#             name='Teachers',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('teachDept', models.CharField(max_length=100)),
#                 ('teachName', models.CharField(max_length=100)),
#                 ('teachImg', models.ImageField(upload_to='teachPics')),
#                 ('teachDesc', models.TextField()),
#             ],
#         ),
#         # migrations.DeleteModel(
#         #     name='Faculties',
#         # ),
#     ]


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachDept', models.CharField(max_length=100)),
                ('teachName', models.CharField(max_length=100)),
                ('teachImg', models.ImageField(upload_to='teachPics')),
                ('teachDesc', models.TextField()),
            ],
        ),
    ]
