# Generated by Django 3.2.9 on 2021-11-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211111_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upDate', models.CharField(max_length=100)),
                ('upTitle', models.CharField(max_length=100)),
                ('upDesc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='teachers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
